name: Deploy Docker Image

on:
   workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Set your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull Docker Image
      run: docker pull ghcr.io/your-username/your-repo:your-tag

    - name: Run Docker Container
      run: docker run -d -p 8080:80 ghcr.io/your-username/your-repo:your-tag
