name: Start EC2 Instance

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Set your default branch

jobs:
  start-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Start EC2 Instance
        env:
          AWS_REGION: us-east-1  # Replace with your AWS region
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          # Start your EC2 instance using the AWS CLI command
          aws ec2 start-instances --region ap-south-1 --instance-ids i-002953cac36e74bd0
          aws ssm send-command --instance-ids "i-002953cac36e74bd0" --region "ap-south-1" --document-name "AWS-RunShellScript" --parameters commands=["echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u sanjayambatkar --password-stdin"]
